[tool.black]
line-length = 100
exclude = '''
^/(
  (
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.venv
    | _build
    | build
    | dist
  )
)
'''

[tool.isort]
profile = "black"
#extend_skip = [".md", ".json"]
#extend_skip = [".tmp", ".venv"]

[tool.mypy]
exclude = "^tests/"
ignore_missing_imports = true

[tool.ruff]
ignore = ["E501"]
extend-exclude = [
  "__pycache__",
  "docs",
  "site",
  "src/dagster_orchestrators/__init__.py",
]
line-length = 100
