name: Known issue
description: Submit a known issue that we can't fix right now
title: "[Known issue]: "
labels: ["bug", "wontfix"]
projects: ["JasperHG90/1"]
body:
  - type: textarea
    id: context
    attributes:
      label: 🐞 Issue
      description: The issue in a nutshell. Why is this creating problems?
    validations:
      required: true
  - type: textarea
    id: whathappens
    attributes:
      label: 💭 What happens?
      description: Describe what happens. How do you know this happens? What is the effect?
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: 💥 What's the impact?
      description: Describe the impact of the issue
    validations:
      required: true
  - type: textarea
    id: cansolve
    attributes:
      label: 🔧 Can we solve it?
      description: Is the problem solvable? If not, explain why
    validations:
      required: true
  - type: textarea
    id: howdeal
    attributes:
      label: 🤷 How will we deal with it?
      description: How are we going to deal with this until a fix is available?
    validations:
      required: true
  - type: textarea
    id: monitor
    attributes:
      label: 🔍 How can we monitor it?
      description: How will we monitor if a fix is available?
    validations:
      required: true
  - type: textarea
    id: otherfixing
    attributes:
      label: 👷‍♀️ Is someone working on it?
      description: GitHub issues, mails etc. Is anyone else working to fix this?
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: 📝 Checklist
      description: Have you done the following?
      options:
        - label: I've linked all relevant issues, PRs, and RFCs where required
          required: true
        - label: I've checked if someone else is working on it
          required: true
