name: Request for comments (RFC)
description: Submit a Request For Comments (RFC)
title: "[RFC]: "
labels: ["enhancement", "proposed"]
projects: ["JasperHG90/1"]
assignees:
  - JasperHG90
body:
  - type: textarea
    id: tldr
    attributes:
      label: 🤓 TL;DR
      description: Add a quick overview of the RFC
    validations:
      required: false
