name: Request for comments (RFC)
description: Submit a Request For Comments (RFC)
title: "[RFC]: "
labels: ["RFC", "proposed"]
projects: ["JasperHG90/1"]
assignees:
  - JasperHG90
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
